-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Account CASCADE;
DROP TABLE IF EXISTS Movie CASCADE;
DROP TABLE IF EXISTS Message CASCADE;
DROP TABLE IF EXISTS Genre CASCADE;
DROP TABLE IF EXISTS MovieGenre CASCADE;
